# RT-Thread building script for RK3576 GPIO

import os

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, os.path.join(cwd, '..')]

group = DefineGroup('Drivers', src, depend=['BSP_USING_GPIO'], CPPPATH=CPPPATH)

Return('group')
