# RT-Thread building script for the onboard WS2812 LEDs

import os

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, os.path.join(cwd, '..')]

group = DefineGroup('Drivers', src, depend=['BSP_USING_WS2812'], CPPPATH=CPPPATH)

Return('group')
